### ISSUE TITLE
Connection refused when using docker

### ISSUE THREAD

**Issue by Gene-Dana** [ClementG63/Neo4Driver#8]
Hi there again ! I'm having issues connecting the driver in a multi-container docker setup..

```dart
/// initialization. Defaults to port 7474
  Neo4jTodosDataSource() {
    NeoClient.withAuthorization(
      username: 'neo4j',
      password: 'password',
      databaseAddress: 'https://127.0.0.1:7474/',
    );
  }

```

docker compose

```
services:
  dart_frog_app:
    build: .
    ports:
      - "8080:8080"

  testneo4j:
    # platform: linux/x86_64
    image: neo4j:latest
    ports:
    - "7474:7474" 
    - "7687:7687"
    volumes:
      - $HOME/neo4j/data:/data
      - $HOME/neo4j/logs:/logs
      - $HOME/neo4j/import:/var/lib/neo4j/import
      - $HOME/neo4j/plugins:/plugins
    environment:
      - NEO4J_AUTH=neo4j/password
```

In Docker, the hostname of the neo4j instance is testneo4j. Is there anyway for the driver to connect via hostname?
